version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16  # Postgres 16 with pgvector pre-installed
    container_name: askflow_db
    environment:
      POSTGRES_USER: askflow_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: askflow_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: